// Project records and the generate step that turns one into a finished video.

import { put, get, remove, uid, blobUrl, getSettings } from './store.js';
import { defaultProject, exportVideo } from './player.js';
import { preparedFace } from './library.js';
import { newContentId, checkRateLimit } from './safety.js';
import { speakPreview, estimateSpeechSeconds } from './voice.js';
import { api } from './api.js';

export async function createProject({ name, sourceVideoId, faceId = null, voiceId = null }) {
  const video = sourceVideoId ? await get('videos', sourceVideoId) : null;
  const edit = defaultProject(video?.duration || 10);
  if (faceId) edit.faceSwap.enabled = true;
  return put('projects', {
    id: uid('proj'),
    name: name || (video ? video.name.replace(/\.[^.]+$/, '') : 'Untitled video'),
    step: 0,
    sourceVideoId,
    faceId,
    voiceId,
    voiceMode: voiceId ? 'clone' : 'none',
    script: '',
    speech: { speed: 1, emotion: 'neutral', tone: 'natural' },
    narration: null,
    music: null,
    musicName: '',
    edit,
    thumb: video?.thumb || null,
    contentId: newContentId(),
    outputVideoId: null,
  });
}

export const saveProject = (p) => put('projects', p);

/**
 * Runs the generative face swap for the whole source video on the AI server and
 * stores the result. The project then uses the swapped footage, and the
 * in-browser overlay is switched off.
 */
export async function runCloudSwap(project, { signal, onProgress } = {}) {
  const src = await get('videos', project.sourceVideoId);
  const face = await get('faces', project.faceId);
  if (!src || !face) throw new Error('Choose a video and a face first.');
  const blob = await api.faceSwapVideo(src.blob, face.blob, { signal, onProgress, duration: src.duration });
  const old = project.cloudSwapVideoId;
  const swapped = await put('videos', {
    id: uid('vid'), kind: 'intermediate', name: `${src.name} (AI face swap)`, blob, mime: blob.type || 'video/mp4',
    duration: src.duration, width: src.width, height: src.height, thumb: src.thumb, consentId: src.consentId,
    faceId: face.id, sourceVideoId: src.id,
  });
  project.cloudSwapVideoId = swapped.id;
  project.cloudSwapFaceId = face.id;
  project.edit.faceSwap.enabled = true;
  await saveProject(project);
  if (old) await remove('videos', old);
  return swapped;
}

/** Everything the Player needs for a project: URLs for media plus the prepared face. */
export async function projectAssets(project) {
  const useSwap = project.cloudSwapVideoId && project.edit.faceSwap.enabled;
  let video = useSwap ? await get('videos', project.cloudSwapVideoId) : null;
  if (useSwap && !video) project.cloudSwapVideoId = null;
  const source = await get('videos', project.sourceVideoId);
  video = video || source;
  if (!video) throw new Error('The source video for this project was deleted.');
  const face = project.faceId && video === source ? await preparedFace(project.faceId) : null;
  const voice = project.voiceId ? await get('voices', project.voiceId) : null;
  const useBrowserVoice = project.voiceMode === 'clone' && !project.narration && voice && project.script.trim();
  return {
    video,
    voice,
    videoUrl: blobUrl(video.id, video.blob),
    // With an AI-swapped video, the original is shown on the "Before" side of the compare slider.
    beforeUrl: video !== source && source ? blobUrl(source.id, source.blob) : null,
    face,
    narrationUrl: project.narration ? blobUrl(project.id + ':narration', project.narration) : null,
    musicUrl: project.music ? blobUrl(project.id + ':music', project.music) : null,
    contentId: project.contentId,
    browserSpeech: useBrowserVoice
      ? () => new Promise(res => speakPreview(voice, project.script, project.speech, { onEnd: res }))
      : null,
  };
}

/** Splits a script into subtitle cues timed across the narration (or the estimated speech length). */
export function subtitlesFromScript(script, { duration, offset = 0, speed = 1 } = {}) {
  const sentences = script.replace(/\s+/g, ' ').trim().match(/[^.!?]+[.!?]*/g) || [];
  // Break long sentences into chunks of ~8 words so cues fit on two lines.
  const chunks = [];
  for (const s of sentences) {
    const w = s.trim().split(' ');
    for (let i = 0; i < w.length; i += 8) chunks.push(w.slice(i, i + 8).join(' '));
  }
  const total = duration || estimateSpeechSeconds(script, speed);
  const chars = chunks.reduce((s, c) => s + c.length, 0) || 1;
  let t = offset;
  return chunks.map(text => {
    const len = total * text.length / chars;
    const cue = { start: +t.toFixed(2), end: +(t + len).toFixed(2), text };
    t += len;
    return cue;
  });
}

export function maxExportHeight() {
  return getSettings().plan === 'free' ? 720 : 1080;
}

/**
 * Renders the project to a finished video and stores it. In cloud mode the
 * face swap is generated by the provider first (full quality), then the edit
 * is rendered on top of that footage.
 */
export async function generateProject(project, { height = 720, onProgress, signal } = {}) {
  const limit = await checkRateLimit();
  if (!limit.ok) throw new Error(`You've reached today's limit of ${limit.limit} videos on your plan. Upgrade or try again tomorrow.`);

  let swapShare = 0;
  if (api.mode === 'cloud' && project.faceId && project.edit.faceSwap.enabled && !project.cloudSwapVideoId) {
    swapShare = 0.6;
    await runCloudSwap(project, { signal, onProgress: (p, s) => onProgress?.(p * swapShare, s || 'AI face swap') });
  }

  const assets = await projectAssets(project);
  const out = await exportVideo(project.edit, assets, {
    height: Math.min(height, maxExportHeight()),
    signal,
    onProgress: (p) => onProgress?.(swapShare + p * (1 - swapShare), 'Rendering video'),
  });

  const rec = await put('videos', {
    id: uid('vid'),
    kind: 'generated',
    name: `${project.name}.${out.mime.includes('mp4') ? 'mp4' : 'webm'}`,
    blob: out.blob,
    mime: out.mime,
    duration: assets.video.duration,
    width: out.width,
    height: out.height,
    thumb: project.thumb,
    projectId: project.id,
    contentId: project.contentId,
    faceId: project.edit.faceSwap.enabled ? project.faceId : null,
    voiceId: project.voiceMode === 'clone' ? project.voiceId : null,
  });
  project.outputVideoId = rec.id;
  project.status = 'generated';
  await saveProject(project);
  return rec;
}

export async function recordExport(video, { quality } = {}) {
  return put('exports', {
    id: uid('exp'),
    videoId: video.id,
    projectId: video.projectId,
    name: video.name,
    contentId: video.contentId,
    size: video.blob.size,
    format: (video.mime || video.blob.type || 'video/webm').split('/')[1],
    quality: quality || `${video.height}p`,
  });
}

export function downloadBlob(blob, name) {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = name;
  document.body.append(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(a.href), 30_000);
}
